sudo: required
services:
  - docker

before_install:
  - docker build -t sydbarrett/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sydbarrett/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-react"
  end: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-1-366225493403"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
